name: AbuseIPDB Badge
version: "1.1.5"
slug: abuseipdb_badge
description: Static page to host AbuseIPDB contributor badge
webui: http://[HOST]:[PORT:8920]
init: false
arch:
- aarch64
- amd64
ports:
  80/tcp: 8920
ports_description:
  80/tcp: Web interface
discovery:
- abuseipdbbadge