name: AbuseIPDB Badge
version: "1.1"
slug: abuseipdb_badge
description: Static page to host AbuseIPDB contributor badge
webui: http://[HOST]:[PORT:3001]
init: false
arch:
- aarch64
- amd64
ports:
  8920/tcp: 8920
ports_description:
  8920/tcp: Web interface
discovery:
- abuseipdbbadge